version: '3'
services:
  people:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongodb-networks
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongodb-networks
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

networks:
  mongodb-networks:
    driver: bridge
