global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9000']
- job_name: golang
  metrics_path: /prometheus
  static_configs:
  - targets:
    - prometheus-ingress:9000
