name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [auth, prometheus, people] # List your projects here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    # Build the project
    - name: Build ${{ matrix.project }} project
      working-directory: ./${{ matrix.project }}
      run: |
        make build
  deploy:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [auth, prometheus, people] # List your projects here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Configure Kubernetes context
      run: |
        echo "${{ secrets.K8S_CA_CERT }}" | base64 -d > ca.crt
        echo "${{ secrets.K8S_CLIENT_CERT }}" | base64 -d > client.crt
        echo "${{ secrets.K8S_CLIENT_KEY }}" | base64 -d > client.key

        kubectl config set-cluster docker-desktop --server=https://localhost:6443 --certificate-authority=ca.crt
        kubectl config set-credentials admin --client-certificate=client.crt --client-key=client.key
        kubectl config set-context docker-desktop --cluster=docker-desktop --user=admin
        kubectl config use-context docker-desktop

    - name: Deployinh ${{ matrix.project }} project
      working-directory: ./${{ matrix.project }}
      run: |
        make install-helm-snbx

  # deploy-snbx:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       project: [auth, prometheus, people] # List your projects here

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: 1.22

  #   # Deploy the projects
  #   - name: Deploying ${{ matrix.project }} project
  #     working-directory: ./${{ matrix.project }}
  #     run: |
  #       make install-helm-snbx

